# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."erpnext-backend" = {
    image = "frappe/erpnext:v16.15.0";
    environment = {
      "DB_HOST" = "db";
      "DB_PORT" = "3306";
      "MARIADB_ROOT_PASSWORD" = "admin";
      "MYSQL_ROOT_PASSWORD" = "admin";
    };
    volumes = [
      "erpnext_logs:/home/frappe/frappe-bench/logs:rw"
      "erpnext_sites:/home/frappe/frappe-bench/sites:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=backend"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-backend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-configurator" = {
    image = "frappe/erpnext:v16.15.0";
    environment = {
      "DB_HOST" = "db";
      "DB_PORT" = "3306";
      "REDIS_CACHE" = "redis-cache:6379";
      "REDIS_QUEUE" = "redis-queue:6379";
      "SOCKETIO_PORT" = "9000";
    };
    volumes = [
      "erpnext_logs:/home/frappe/frappe-bench/logs:rw"
      "erpnext_sites:/home/frappe/frappe-bench/sites:rw"
    ];
    cmd = [ "ls -1 apps > sites/apps.txt; bench set-config -g db_host $DB_HOST; bench set-config -gp db_port $DB_PORT; bench set-config -g redis_cache \"redis://$REDIS_CACHE\"; bench set-config -g redis_queue \"redis://$REDIS_QUEUE\"; bench set-config -g redis_socketio \"redis://$REDIS_QUEUE\"; bench set-config -gp socketio_port $SOCKETIO_PORT;
  " ];
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"bash\", \"-c\"]"
      "--network-alias=configurator"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-configurator" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-create-site" = {
    image = "frappe/erpnext:v16.15.0";
    volumes = [
      "erpnext_logs:/home/frappe/frappe-bench/logs:rw"
      "erpnext_sites:/home/frappe/frappe-bench/sites:rw"
    ];
    cmd = [ "wait-for-it -t 120 db:3306; wait-for-it -t 120 redis-cache:6379; wait-for-it -t 120 redis-queue:6379; export start=`date +%s`; until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r \".db_host // empty\"` ]] && \\
    [[ -n `grep -hs ^ sites/common_site_config.json | jq -r \".redis_cache // empty\"` ]] && \\
    [[ -n `grep -hs ^ sites/common_site_config.json | jq -r \".redis_queue // empty\"` ]];
  do
    echo \"Waiting for sites/common_site_config.json to be created\";
    sleep 5;
    if (( `date +%s`-start > 120 )); then
      echo \"could not find sites/common_site_config.json with required keys\";
      exit 1
    fi
  done; echo \"sites/common_site_config.json found\"; bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;
  " ];
    log-driver = "journald";
    extraOptions = [
      "--entrypoint=[\"bash\", \"-c\"]"
      "--network-alias=create-site"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-create-site" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-db" = {
    image = "mariadb:11.8";
    environment = {
      "MARIADB_ROOT_PASSWORD" = "admin";
      "MYSQL_ROOT_PASSWORD" = "admin";
    };
    volumes = [
      "erpnext_db-data:/var/lib/mysql:rw"
    ];
    cmd = [ "--character-set-server=utf8mb4" "--collation-server=utf8mb4_unicode_ci" "--skip-character-set-client-handshake" ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"healthcheck.sh\", \"--connect\", \"--innodb_initialized\"]"
      "--health-interval=5s"
      "--health-retries=5"
      "--health-start-period=5s"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_db-data.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_db-data.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-frontend" = {
    image = "frappe/erpnext:v16.15.0";
    environment = {
      "BACKEND" = "backend:8000";
      "CLIENT_MAX_BODY_SIZE" = "50m";
      "FRAPPE_SITE_NAME_HEADER" = "frontend";
      "PROXY_READ_TIMEOUT" = "120";
      "SOCKETIO" = "websocket:9000";
      "UPSTREAM_REAL_IP_ADDRESS" = "127.0.0.1";
      "UPSTREAM_REAL_IP_HEADER" = "X-Forwarded-For";
      "UPSTREAM_REAL_IP_RECURSIVE" = "off";
    };
    volumes = [
      "erpnext_logs:/home/frappe/frappe-bench/logs:rw"
      "erpnext_sites:/home/frappe/frappe-bench/sites:rw"
    ];
    ports = [
      "8080:8080/tcp"
    ];
    cmd = [ "nginx-entrypoint.sh" ];
    dependsOn = [
      "erpnext-websocket"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=frontend"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-frontend" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-queue-long" = {
    image = "frappe/erpnext:v16.15.0";
    environment = {
      "FRAPPE_REDIS_CACHE" = "redis://redis-cache:6379";
      "FRAPPE_REDIS_QUEUE" = "redis://redis-queue:6379";
    };
    volumes = [
      "erpnext_logs:/home/frappe/frappe-bench/logs:rw"
      "erpnext_sites:/home/frappe/frappe-bench/sites:rw"
    ];
    cmd = [ "bench" "worker" "--queue" "long,default,short" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=queue-long"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-queue-long" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-queue-short" = {
    image = "frappe/erpnext:v16.15.0";
    environment = {
      "FRAPPE_REDIS_CACHE" = "redis://redis-cache:6379";
      "FRAPPE_REDIS_QUEUE" = "redis://redis-queue:6379";
    };
    volumes = [
      "erpnext_logs:/home/frappe/frappe-bench/logs:rw"
      "erpnext_sites:/home/frappe/frappe-bench/sites:rw"
    ];
    cmd = [ "bench" "worker" "--queue" "short,default" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=queue-short"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-queue-short" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-redis-cache" = {
    image = "redis:6.2-alpine";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=redis-cache"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-redis-cache" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-redis-queue" = {
    image = "redis:6.2-alpine";
    volumes = [
      "erpnext_redis-queue-data:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=redis-queue"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-redis-queue" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_redis-queue-data.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_redis-queue-data.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-scheduler" = {
    image = "frappe/erpnext:v16.15.0";
    volumes = [
      "erpnext_logs:/home/frappe/frappe-bench/logs:rw"
      "erpnext_sites:/home/frappe/frappe-bench/sites:rw"
    ];
    cmd = [ "bench" "schedule" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=scheduler"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-scheduler" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };
  virtualisation.oci-containers.containers."erpnext-websocket" = {
    image = "frappe/erpnext:v16.15.0";
    environment = {
      "FRAPPE_REDIS_CACHE" = "redis://redis-cache:6379";
      "FRAPPE_REDIS_QUEUE" = "redis://redis-queue:6379";
    };
    volumes = [
      "erpnext_logs:/home/frappe/frappe-bench/logs:rw"
      "erpnext_sites:/home/frappe/frappe-bench/sites:rw"
    ];
    cmd = [ "node" "/home/frappe/frappe-bench/apps/frappe/socketio.js" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=websocket"
      "--network=erpnext_frappe_network"
    ];
  };
  systemd.services."podman-erpnext-websocket" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = lib.mkOverride 90 0;
    };
    after = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    requires = [
      "podman-network-erpnext_frappe_network.service"
      "podman-volume-erpnext_logs.service"
      "podman-volume-erpnext_sites.service"
    ];
    partOf = [
      "podman-compose-erpnext-root.target"
    ];
    wantedBy = [
      "podman-compose-erpnext-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-erpnext_frappe_network" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f erpnext_frappe_network";
    };
    script = ''
      podman network inspect erpnext_frappe_network || podman network create erpnext_frappe_network --driver=bridge
    '';
    partOf = [ "podman-compose-erpnext-root.target" ];
    wantedBy = [ "podman-compose-erpnext-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-erpnext_db-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect erpnext_db-data || podman volume create erpnext_db-data
    '';
    partOf = [ "podman-compose-erpnext-root.target" ];
    wantedBy = [ "podman-compose-erpnext-root.target" ];
  };
  systemd.services."podman-volume-erpnext_logs" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect erpnext_logs || podman volume create erpnext_logs
    '';
    partOf = [ "podman-compose-erpnext-root.target" ];
    wantedBy = [ "podman-compose-erpnext-root.target" ];
  };
  systemd.services."podman-volume-erpnext_redis-queue-data" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect erpnext_redis-queue-data || podman volume create erpnext_redis-queue-data
    '';
    partOf = [ "podman-compose-erpnext-root.target" ];
    wantedBy = [ "podman-compose-erpnext-root.target" ];
  };
  systemd.services."podman-volume-erpnext_sites" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect erpnext_sites || podman volume create erpnext_sites
    '';
    partOf = [ "podman-compose-erpnext-root.target" ];
    wantedBy = [ "podman-compose-erpnext-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-erpnext-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
